version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: .docker/ror/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/ror
    ports:
      - "3000:3000"
    depends_on:
      - database
      - ngrok
    expose:
      - "3000"

  ngrok:
    image: ngrok/ngrok:latest
    environment:
        NGROK_AUTHTOKEN: ''
    command: 'http web:3000 --domain=oyinda.ngrok.app'
    ports:
        - '4040:4040'
    expose:
        - '4040'
